### ISSUE TITLE
Undefined is not an object (evaluating 'RNMailCompose.name')

### ISSUE THREAD

**Issue by foysalit** [joonhocho/react-native-mail-compose#4]
I have followed your setup guide for ios but getting the error shown in the image below. Can you please help me out fixing this issue?

![simulator screen shot 14 aug 2017 12 35 04](https://user-images.githubusercontent.com/1919066/29268377-cb9859b4-80ec-11e7-8e86-b549efa84936.png)

**Comment by joonhocho** [comment]
@foysalit Have you setup swift bridge properly? take a look at ExampleApp.

**Comment by michelle0927** [comment]
I'm having this issue as well. I've set up the bridging header as instructed. Any ideas?

**Comment by foysalit** [comment]
Looks like it *was* a bridging header issue. I had to redo the bridging part and that fixed it. Try fixing your bridging header and follow every step carefully and it should work out @michelle0927

**Comment by atmoio** [comment]
I've followed the steps carefully many times, but I'm still seeing this issue. @foysalit can you comment on what particular steps you took or if there's anything I should be checking?

**Comment by foysalit** [comment]
I followed these steps - https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html and seems to have worked for me.

**Comment by michelle0927** [comment]
I've tried recreating the bridging header as well as recreating the project many times, and still receive the same error. @mobitar if you figure out a solution, would you mind posting your findings?

**Comment by atmoio** [comment]
I ended up forking another library and adding what I liked from this library (which was the ability to pass attachment data as a base64 string and not a file.)

https://github.com/mobitar/react-native-mail

**Comment by sakarit-zz** [comment]
I'm having this issue as well. I have tried many times but nothing seems to work... I'm using Xcode 9.0.

**Comment by sakarit-zz** [comment]
@joonhocho What to do?

**Comment by nicolasgalano** [comment]
@foysalit can you please propose an update on the readme file? adding the steps you took from the documentation provided?

**Comment by nicolasgalano** [comment]
@joonhocho is it posible to place this 3 files:
https://github.com/joonhocho/react-native-mail-compose/tree/master/ios/RNMailCompose

inside an xcodeproj ? to make if work as a Framework or Library?
https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/CreatingFrameworks.html

My knowledge is not enough for this

**Comment by joonhocho** [comment]
@nicolasgalano AS far as I know, Swift doesn't support library yet.

**Comment by nicolasgalano** [comment]
![image](https://user-images.githubusercontent.com/1795431/32350927-827570a8-bffa-11e7-86b3-deda30a782b6.png)
![image](https://user-images.githubusercontent.com/1795431/32350952-9d9bbab8-bffa-11e7-8dba-f4a15fde488c.png)
Would you say there is something I'm missing here?
I'm still getting the "Undefined is not an object (evaluating 'RNMailCompose.name')" error after I follow all the steps.

PD:  Also the "how to create one(Swift Bridging Header)" is not working,
http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/
I used this one instead:
https://bohemianpolymorph.wordpress.com/2014/07/11/manually-adding-a-swift-bridging-header/
And then this one too:
https://mycodetips.com/ios/manually-adding-swift-bridging-header-1290.html

Thanks for the quick respond :)

**Comment by joonhocho** [comment]
![screen shot 2017-11-02 at 3 00 43 pm](https://user-images.githubusercontent.com/930795/32352497-b0c0255a-bfde-11e7-9a8f-23cc47589c02.png)

@nicolasgalano 

Do you see RNMailCompose files under `Compile Sources` on your right target?

Have you restarted your react native packager with `--reset-cache` option?

Is `ExampleApp` working on your machine?

**Comment by nicolasgalano** [comment]
No they are not been added,
![image](https://user-images.githubusercontent.com/1795431/32358968-e08237de-c028-11e7-8850-0bd82d895a0d.png)
How should I add them?

Yes I had, but the error is still appearing 

I hadn't run that Example project yet :(

**Comment by nicolasgalano** [comment]
@joonhocho 
Got it to work!

Here are my bulletproof steps:

- First of all we need to get the Swift Bridging Header created, here is the link I used to accomplish that:
https://bohemianpolymorph.wordpress.com/2014/07/11/manually-adding-a-swift-bridging-header/

1. Copy files from inside the folder: "{YourApp}/node_modules/react-native-mail-compose/ios/RNMailCompose." (I did this by dragging them) into the root of your project in XCode (by doing this we have to check if the files got added under "Build Phases">"Compile Sources").
![image](https://user-images.githubusercontent.com/1795431/32381490-8ad45718-c091-11e7-99df-58d8767357d1.png)
2. Create a "Group" in the root of your project in XCode, like this: (call it RNMailComposer)
![image](https://user-images.githubusercontent.com/1795431/32381185-ddd3dcf0-c090-11e7-8935-12efe57d32dd.png)
3. Then in XCode drag the files we pasted in the root, inside that folder/group.
![image](https://user-images.githubusercontent.com/1795431/32381397-56655f2c-c091-11e7-99f7-2fd0f63ad897.png)
4. (from joonhocho's) Add to your Swift Bridging Header, {YourApp}/ios/{YourApp}-Bridging-Header.h:
#import <React/RCTBridgeModule.h>
#import <React/RCTViewManager.h>
#import <React/RCTEventEmitter.h>


Hope this helps!

**Comment by OlegPanfyorov** [comment]
@nicolasgalano Your instruction works great! Original one should be replaced by this one!

**Comment by devagul93** [comment]
@nicolasgalano Your instruction works great! Original one should be replaced by this one!
